services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-php
    ports:
      - "8280:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
